@startuml
class CartItem {
- IProduct product
- int quantity
+ void changeQuantity(int)
+ double calculateSubtotal()
+ IProduct getProduct()
+ int getQuantity()
}


class ShoppingCart {
- List<CartItem> items
- Date createTime
+ void setCreateTime(Date)
+ Date getCreateTime()
~ void addProducts(CartItem,Map<String,IProduct>)
~ void removeProduct(CartItem)
~ void modifyQuantity(CartItem,int)
+ String calculateTotalAmount()
+ void emptyCart()
~ List<CartItem> getItems()
~ Order getOrder(IProduct)
+ void printItems()
}


class ProductHouse {
- Map<String,IProduct> products
~ boolean addProduct(IProduct)
~ IProduct getProduct(String)
+ boolean removeProduct(String)
+ void readProducts()
+ void readSortedProducts(String)
+ void readNameProducts(String)
~ Map<String,IProduct> returnProducts()
}


enum OrderStatus {
+  CREATED
+  PAID
+  SHIPPED
+  RECEIVED
+  CANCELLED
- int code
- String description
+ int getCode()
+ String getDescription()
+ {static} OrderStatus getByCode(int)
+ {static} OrderStatus getByDescription(String)
}


class OrderList {
- ArrayList<Order> orderList
+ void addOrder(Order)
+ void removeOrder(Order)
+ void showAllOrders()
+ ArrayList<Order> returnOrders()
+ Order getOrder(String)
}


class Main {
~ {static} ProductHouse ph
~ {static} ShoppingCart sc
~ {static} OrderList ol
~ {static} boolean usAndma
~ {static} Scanner scanner
+ {static} void main(String[])
+ {static} void mainMenu()
+ {static} void managerMune()
+ {static} void userMenu()
+ {static} void productsBrowse()
+ {static} void productAdd()
+ {static} void productRemove()
+ {static} void cartAdd()
+ {static} void cartManager()
+ {static} void orderPlace()
+ {static} void myOrder()
+ {static} void orderManager()
}


interface IProduct {
~ String getId()
~ String getName()
~ double getPrice()
~ int getStock()
~ String getCategory()
~ void setStock(int)
~ void setCategory(String)
~ void setName(String)
~ void setPrice(double)
~ void setId(String)
}

class Product {
- String id
- String name
- double price
- int stock
- String category
+ String getId()
+ String getName()
+ double getPrice()
+ int getStock()
+ String getCategory()
+ void setStock(int)
+ void setCategory(String)
+ void setName(String)
+ void setPrice(double)
+ void setId(String)
}


class ProductFactory {
~ {static} Product createProduct(String,String,double,int,String)
}

class Order {
- String orderId
- CartItem item
- Date orderTime
- double totalAmount
- Short status
+ void pay()
~ void deliver(Map<String,IProduct>)
+ void receive()
~ void cancel(Map<String,IProduct>)
+ double getTotalAmount()
+ String getOrderId()
~ CartItem getItem()
+ Date getOrderTime()
+ Short getStatus()
+ void setOrderTime()
}




IProduct <|.. Product
@enduml